//
// Created by MurphySL on 2020/9/14.
//

#ifndef WEAVESS_POLICY_H
#define WEAVESS_POLICY_H

namespace weavess {
    enum TYPE {
        INIT_NN_DESCENT, INIT_RANDOM, INIT_KDT, INIT_HCNNG,
        REFINE_NSG, REFINE_NSSG, REFINE_DPG, REFINE_EFANNA, REFINE_HNSW, REFINE_VAMANA, REFINE_NN_DESCENT, REFINE_OTHER,
        ENTRY_RANDOM, ENTRY_NSG_CENTROID, ENTRY_NSSG_CENTROID,
        CANDIDATE_GREEDY, CANDIDATE_NONE, CANDIDATE_PROPAGATION2,
        PRUNE_NSG, PRUNE_NSSG, PRUNE_DPG, PRUNE_HEURISTIC, PRUNE_NAIVE, PRUNE_VAMANA,
        ROUTER_GREEDY, ROUTE_GUIED
    };
}

#endif //WEAVESS_POLICY_H
