//
// Created by MurphySL on 2020/10/23.
//

#ifndef WEAVESS_POLICY_H
#define WEAVESS_POLICY_H

namespace weavess {
    enum TYPE {
        INDEX_KGRAPH, INDEX_FANNG, INDEX_NSG, INDEX_SSG, INDEX_DPG, INDEX_VAMANA, INDEX_EFANNA, INDEX_IEH,
        INDEX_NSW, INDEX_HNSW, INDEX_ONNG, INDEX_PANNG, INDEX_HCNNG, INDEX_SPTAG_KDT, INDEX_SPTAG_BKT, INDEX_EXACT_KNNG, INDEX_KDRG,


        INIT_RANDOM, INIT_KNNG, INIT_KDT,

        REFINE_NN_DESCENT, REFINE_KDRG,




        INIT_NN_DESCENT, INIT_RAND, INIT_IEH, INIT_NSW, INIT_HNSW, INIT_ANNG, INIT_SPTAG_KDT, INIT_SPTAG_BKT, INIT_FANNG, INIT_HCNNG,

        REFINE_NSG, REFINE_SSG, REFINE_DPG, REFINE_VAMANA, REFINE_EFANNA, REFINE_PANNG, REFINE_SPTAG_KDT, REFINE_SPTAG_BKT, REFINE_FANNG, REFINE_ONNG,

        SEARCH_ENTRY_RAND, SEARCH_ENTRY_CENTROID, SEARCH_ENTRY_SUB_CENTROID, SEARCH_ENTRY_KDT, SEARCH_ENTRY_KDT_SINGLE, SEARCH_ENTRY_NONE, SEARCH_ENTRY_HASH,
        SEARCH_ENTRY_SPTAG_KDT, SEARCH_ENTRY_SPTAG_BKT, SEARCH_ENTRY_VPT,

        L_SEARCH_ASCEND, L_SEARCH_SET_RECALL, L_SEARCH_ASSIGN,

        ROUTER_GREEDY, ROUTER_IEH, ROUTER_NSW, ROUTER_HNSW, ROUTER_NGT, ROUTER_BACKTRACK, ROUTER_SPTAG_KDT, ROUTER_SPTAG_BKT, ROUTER_GUIDE


    };
}

#endif //WEAVESS_POLICY_H
